### ISSUE TITLE
Bug Report: <BUG> 17.0.8 error with image

### ISSUE THREAD

**Issue by Matcham89** [CircleCI-Public/cimg-openjdk#158] opened 2023-07-21 14:24 UTC
*Note: We also welcome PRs to fix bugs! This helps us take action faster where a bug has been identified!*

For our official CircleCI Docker Convenience Image support policy, please see [CircleCI docs](https://circleci.com/docs/convenience-images-support-policy).

This policy outlines the release, update, and deprecation policy for CircleCI Docker Convenience Images.

---

**Describe the bug**

Since the update to 17.0.8, the CircleCi pipeline is failing to find the image 
This happens when you define  `17.0` or `17.0.8`
```bash
"CircleCI failed to run this build, check your config. Try re-running the build and if this issue persists, open a [Support ticket](https://support.circleci.com/hc/en-us). Detail: The task failed Error response from daemon: manifest for cimg/openjdk:17.0 not found"
```
It can not find the image

Typically the "17.0" should bring through the latest version, but since the update on 20/07/23, the pipeline fails.
```bash
defaults:
  default_executor: &default_executor
    docker:
      - image: cimg/openjdk:17.0
```

Looking at the below URL `17.0.8` is ZERO in size
https://circleci.com/developer/images/image/cimg/openjdk?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQjw2eilBhCCARIsAG0Pf8tcuFLmKZ2Ohy6IFxMaTfcEuvE4fss5M5uSqfGj6HDX5oBMyAlWs90aAhPdEALw_wcB

**To Reproduce**
Please provide steps to reproduce the behavior, such as a sample job or config file.

Run config.yml file with the below as the default executor
```bash
defaults:
  default_executor: &default_executor
    docker:
      - image: cimg/openjdk:17.0
```

**Expected behavior**

The default executor with pull the latest version and work without error

**Workarounds**
Are there any current workarounds for this bug that can be used currently?

hardcode the version to the previous
17.0.7

**Screenshots and Build Links**
If possible, add screenshots and links to jobs to help explain your problem.
<img width="904" alt="Screenshot 2023-07-21 at 15 21 48" src="https://github.com/CircleCI-Public/cimg-openjdk/assets/87593715/961b3170-4ec7-4aa8-91b8-1ed6b76f0eda">

<img width="1209" alt="Screenshot 2023-07-21 at 15 21 23" src="https://github.com/CircleCI-Public/cimg-openjdk/assets/87593715/275773a1-66a8-412e-a40b-688cf871d07f">

**Additional context**

**Comment by BytesGuy** [comment] 2023-09-03 23:49
Hi, I am not able to reproduce this on either Intel or ARM docker, please see attached:

<img width="733" alt="Screenshot 2023-09-04 at 00 45 49" src="https://github.com/CircleCI-Public/cimg-openjdk/assets/955076/8307b153-c3aa-4eaa-b60a-bc8b803d56cd">

<img width="733" alt="Screenshot 2023-09-04 at 00 45 43" src="https://github.com/CircleCI-Public/cimg-openjdk/assets/955076/1e475e95-88fb-4979-a9da-7e5a9a28d359">

If you are still facing this issue, please open a support ticket so the support team can investigate further.

As for the image size issue, this is a problem with the developer hub, not the image itself. The image sizes are correct on Dockerhub: https://hub.docker.com/layers/cimg/openjdk/17.0.8/images/sha256-636ba84fbc06da072f6c48b0be7ef205de36eb1091f090c9b7255f6d95d8350c?context=explore

I would suggest opening an issue with the docs team here: https://github.com/circleci/circleci-docs

As this cannot be reproduced, I will close this issue, please contact support if this is still occurring. Thanks!

**Closed by BytesGuy** 2023-09-03 23:49 UTC
Labels: bug
